// GENERATED by scripts/gen-data.mjs from tasks/reference/assets.json. Do not edit by hand (npm run gen).
export type ImageId = 'IMG-01' | 'IMG-02' | 'IMG-03' | 'IMG-04' | 'IMG-05' | 'IMG-06' | 'IMG-07' | 'IMG-08' | 'IMG-09' | 'IMG-10' | 'IMG-11' | 'IMG-12' | 'IMG-13' | 'IMG-14' | 'IMG-15' | 'IMG-16' | 'IMG-17' | 'IMG-18' | 'IMG-19' | 'IMG-20'
export type VideoId = 'VID-01' | 'VID-02' | 'VID-03'
export interface ImageAsset { id: ImageId; src: string; alt: string; credit: string; license: string; creditRequired: boolean; sourcePage: string; usedIn: string; width: number; height: number }
export interface VideoAsset { id: VideoId; youtubeId: string; title: string; channel: string; embed: string; poster: string; usedIn: string }
const B = import.meta.env.BASE_URL
export const images: Record<ImageId, ImageAsset> = {
  "IMG-01": {
    "id": "IMG-01",
    "src": B + "img/IMG-01.webp",
    "alt": "ESP32 development board",
    "credit": "Edwiyanto",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:ESP32_Dev_Board.jpg",
    "usedIn": "Hardware lab, BA011/IA013 context",
    "width": 1440,
    "height": 1920
  },
  "IMG-02": {
    "id": "IMG-02",
    "src": B + "img/IMG-02.webp",
    "alt": "ESP-WROOM-32 Wi-Fi/BT module",
    "credit": "Brian Krent",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Espressif_ESP-WROOM-32_Wi-Fi_%26_Bluetooth_Module.jpg",
    "usedIn": "Teardown hotspot: the radio",
    "width": 800,
    "height": 800
  },
  "IMG-03": {
    "id": "IMG-03",
    "src": B + "img/IMG-03.webp",
    "alt": "ESP8266 Wi-Fi module",
    "credit": "Suyash Dwivedi",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:ESP8266_module_01.jpg",
    "usedIn": "Heritage: the first boards (2015)",
    "width": 1600,
    "height": 1200
  },
  "IMG-04": {
    "id": "IMG-04",
    "src": B + "img/IMG-04.webp",
    "alt": "Raspberry Pi 4 Model B, top",
    "credit": "Laserlicht",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Raspberry_Pi_4_Model_B_-_Top.jpg",
    "usedIn": "IA002/IA003 RPi HAT context",
    "width": 1600,
    "height": 1068
  },
  "IMG-05": {
    "id": "IMG-05",
    "src": B + "img/IMG-05.webp",
    "alt": "Circuit board macro",
    "credit": "Ingo Dierking",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Macro_circuit_board.JPG",
    "usedIn": "Hero texture, section backgrounds",
    "width": 1600,
    "height": 1067
  },
  "IMG-06": {
    "id": "IMG-06",
    "src": B + "img/IMG-06.webp",
    "alt": "Green circuit board",
    "credit": "Peter Shanks from Hobart, Australia",
    "license": "CC BY 2.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Green_circuit_board_II_(2389301870).jpg",
    "usedIn": "Background texture",
    "width": 1600,
    "height": 1200
  },
  "IMG-07": {
    "id": "IMG-07",
    "src": B + "img/IMG-07.webp",
    "alt": "Siemens PLC in a cabinet",
    "credit": "BreakdownDiode",
    "license": "CC BY-SA 3.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Siemens_PLC_Nov.5,2013.jpg",
    "usedIn": "IA015 'Retro to IIoT' legacy-PLC story",
    "width": 1600,
    "height": 1200
  },
  "IMG-08": {
    "id": "IMG-08",
    "src": B + "img/IMG-08.webp",
    "alt": "Siemens Simatic S7-416-3 PLC",
    "credit": "Mixabest",
    "license": "Public domain",
    "creditRequired": false,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Siemens_Simatic_S7-416-3.jpg",
    "usedIn": "Legacy PLC, retrofit section",
    "width": 1243,
    "height": 1920
  },
  "IMG-09": {
    "id": "IMG-09",
    "src": B + "img/IMG-09.webp",
    "alt": "DIN-rail power terminals",
    "credit": "Dmitry G",
    "license": "CC BY-SA 3.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Power_terminals_for_DIN_rail.JPG",
    "usedIn": "Industrial mounting context",
    "width": 1600,
    "height": 1200
  },
  "IMG-10": {
    "id": "IMG-10",
    "src": B + "img/IMG-10.webp",
    "alt": "DIN-rail clamp terminals",
    "credit": "Dmitry G",
    "license": "CC BY-SA 3.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:OUNEVA_TO21771_block_of_clamp_terminals_for_DIN_rail.JPG",
    "usedIn": "Industrial detail",
    "width": 1600,
    "height": 1200
  },
  "IMG-11": {
    "id": "IMG-11",
    "src": B + "img/IMG-11.webp",
    "alt": "Robotic arm on a factory line",
    "credit": "Henrysz",
    "license": "CC BY 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Robotic_Arm_Polishing_Guitars_at_Martin_Guitar_Factory.jpg",
    "usedIn": "Industry 4.0 / robotics",
    "width": 1280,
    "height": 1920
  },
  "IMG-12": {
    "id": "IMG-12",
    "src": B + "img/IMG-12.webp",
    "alt": "LoRa IoT gateway station",
    "credit": "-stk",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Kerlink_LoRa_IoT_Station_868_P1110449.jpg",
    "usedIn": "IA005/IA013 LoRa section",
    "width": 1600,
    "height": 1067
  },
  "IMG-13": {
    "id": "IMG-13",
    "src": B + "img/IMG-13.webp",
    "alt": "LoRaWAN deployment diagram",
    "credit": "Roujiamo87",
    "license": "CC0",
    "creditRequired": false,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Representative_LoRaWAN_Deployment_with_Gateway_%2B_End_Device.png",
    "usedIn": "Reference for the network diagram",
    "width": 1600,
    "height": 1235
  },
  "IMG-14": {
    "id": "IMG-14",
    "src": B + "img/IMG-14.webp",
    "alt": "PLC 8-point relay output module",
    "credit": "Mithilrkadam",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:PLC_Output_module_8_point_relay_hardware.jpg",
    "usedIn": "Relay / BA012 context",
    "width": 311,
    "height": 560
  },
  "IMG-15": {
    "id": "IMG-15",
    "src": B + "img/IMG-15.webp",
    "alt": "5V single relay module",
    "credit": "Suyash Dwivedi",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:SRD-05VDC-SL-C_5V_one-channel_relay_module.jpg",
    "usedIn": "Relay detail",
    "width": 1600,
    "height": 1068
  },
  "IMG-16": {
    "id": "IMG-16",
    "src": B + "img/IMG-16.webp",
    "alt": "SMD components on a wave-soldered PCB",
    "credit": "wdwd",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:SMD_circuit_on_a_wave_soldered_PCB.JPG",
    "usedIn": "Manufacturing / quality section",
    "width": 1224,
    "height": 827
  },
  "IMG-17": {
    "id": "IMG-17",
    "src": B + "img/IMG-17.webp",
    "alt": "Electronics lab bench",
    "credit": "Chiara Coetzee from Menlo Park, CA, USA",
    "license": "CC0",
    "creditRequired": false,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Electronics_equipment_for_demo_at_Par_Lab_retreat_(8443570446).jpg",
    "usedIn": "Engineering lab / custom design services",
    "width": 1600,
    "height": 1068
  },
  "IMG-18": {
    "id": "IMG-18",
    "src": B + "img/IMG-18.webp",
    "alt": "Oscilloscope on a lab bench",
    "credit": "Peter Seligman",
    "license": "CC BY-SA 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:BWD_530A_oscilloscope_and_Mini-Lab.jpg",
    "usedIn": "Testing and validation",
    "width": 1600,
    "height": 1200
  },
  "IMG-19": {
    "id": "IMG-19",
    "src": B + "img/IMG-19.webp",
    "alt": "Panorama of Hubballi from Nrupatunga Hill",
    "credit": "Syed Zohaibullah",
    "license": "CC BY-SA 3.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:Panoramic_View_of_Hubli_City_from_Nrupatunga_Hill.jpg",
    "usedIn": "About: made in Hubballi",
    "width": 1600,
    "height": 834
  },
  "IMG-20": {
    "id": "IMG-20",
    "src": B + "img/IMG-20.webp",
    "alt": "Industrial control cabinet",
    "credit": "Rubin Observatory/NSF/AURA",
    "license": "CC BY 4.0",
    "creditRequired": true,
    "sourcePage": "https://commons.wikimedia.org/wiki/File:M1M3_Cabinet_Delivery_to_CAID_(rubin-cabinet-at-caid).jpg",
    "usedIn": "Control cabinet / integration",
    "width": 1600,
    "height": 1200
  }
}
export const videos: Record<VideoId, VideoAsset> = {
  "VID-01": {
    "id": "VID-01",
    "youtubeId": "ejHe_RNPfnE",
    "title": "ESP8266 Dimmer + Relay from Armtronix Review - Baba Awesam",
    "channel": "Samir Sogay",
    "embed": "https://www.youtube-nocookie.com/embed/ejHe_RNPfnE",
    "poster": "https://i.ytimg.com/vi/ejHe_RNPfnE/hqdefault.jpg",
    "usedIn": "Third-party review: dimmer + relay"
  },
  "VID-02": {
    "id": "VID-02",
    "youtubeId": "bJfX521q4Ck",
    "title": "4 Port ESP8266 Relay Module from Armtronix Review - Baba Awesam",
    "channel": "Samir Sogay",
    "embed": "https://www.youtube-nocookie.com/embed/bJfX521q4Ck",
    "poster": "https://i.ytimg.com/vi/bJfX521q4Ck/hqdefault.jpg",
    "usedIn": "Third-party review: 4-port relay"
  },
  "VID-03": {
    "id": "VID-03",
    "youtubeId": "n8z6AHKdl4o",
    "title": "ESP8266 Relay from Armtronix Review - Baba Awesam",
    "channel": "Samir Sogay",
    "embed": "https://www.youtube-nocookie.com/embed/n8z6AHKdl4o",
    "poster": "https://i.ytimg.com/vi/n8z6AHKdl4o/hqdefault.jpg",
    "usedIn": "Third-party review: relay"
  }
}
